### ISSUE TITLE
Error while upgrading RH package to latest spandx version

### ISSUE THREAD

**Issue by adithyaakrishna** [redhataccess/spandx#251]
@mwcz I was trying to update the `spandx` version to the latest one i.e. `2.2.2` but I am getting this error when I try to run the app locally 😶 

```
> @rh-support/customer-support@1.3.13 start:dev /Users/adikris/Desktop/RedHat/PCM/solution-engine-app/apps/customer-support
> webpack-dev-server --config ./node_modules/@rh-support/configs/apps/webpack-dev.js --https --cert ./node_modules/@rh-support/configs/apps/server.cert --key ./node_modules/@rh-support/configs/apps/server.key --hot --inline --profile --progress --bail & spandx -c ./node_modules/@rh-support/configs/apps/spandx.config.js

/Users/adikris/Desktop/RedHat/PCM/solution-engine-app/apps/customer-support/node_modules/token-slice/dist/tsc/main.js:4
export class TokenSlicer {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/adikris/Desktop/RedHat/PCM/solution-engine-app/apps/customer-support/node_modules/spandx/app/chromeMiddleware.js:2:31)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rh-support/customer-support@1.3.13 start:dev: `webpack-dev-server --config ./node_modules/@rh-support/configs/apps/webpack-dev.js --https --cert ./node_modules/@rh-support/configs/apps/server.cert --key ./node_modules/@rh-support/configs/apps/server.key --hot --inline --profile --progress --bail & spandx -c ./node_modules/@rh-support/configs/apps/spandx.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @rh-support/customer-support@1.3.13 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/adikris/.npm/_logs/2021-12-06T15_32_56_893Z-debug.log
```

**Comment by mwcz** [comment]
Hi @adithyaakrishna, it looks like the tooling in your project (probably webpack) is trying to include the ESM module from the [token-slice](https://www.npmjs.com/package/token-slice) package.  token-slice uses the `exports` field in package.json to provide an [ESM and CJS module](https://github.com/redhataccess/token-slice/blob/c64a1b469d0189a49b898823dc9aa8bed280e89e/package.json#L9-L12) which your tooling should pick up on automatically, but that appears to be failing.

I don't use webpack much but it looks like webpack 4 doesn't support package.json's `exports` field, but webpack 5 does.

**Comment by mwcz** [comment]
Thanks for the PR.  Got lucky this time, since it was an unused dependency.  But if you encounter this problem again with some other dependency, upgrading nodejs _should_ help.

**Comment by adithyaakrishna** [comment]
Okay sure, Thank You @mwcz :)
